version: '3.9'
name: tor-clone
services:

# ==== CLIENT ====

  client:
    build:
      context: .
      dockerfile: ./client/client.Dockerfile
    ports:
      - "8080:8080" # This is forwarding the connection to port 8080 in local machine, if there was any port collision just change it to "yourport:8080"
    depends_on:
      directory:
        condition: service_healthy

# ==================

# ==== DIRECTORY ====

  directory:
    build: 
      context: ./directory
      dockerfile: directory.Dockerfile
    ports:
      - "8081:8080"  # This is forwarding the connection to port 8081 in local machine, if there was any port collision just change it to "yourport:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 15s
      retries: 5

# ==================

# ==== END SERVER ====

  end-server:
    build: 
      context: ./end_server
      dockerfile: end_server.Dockerfile
    ports:
      - "8082:8080"  # This is forwarding the connection to port 8082 in local machine, if there was any port collision just change it to "yourport:8080"
    depends_on:
      directory:
        condition: service_healthy
        
# ==================

# ==== ENTRY NODES =====

  entry-0: 
    build:
      context: .
      dockerfile: entry/entry.Dockerfile
    environment:
      - PORT=9999  # We can specify what port this node will use
    depends_on:
      directory:
        condition: service_healthy

 # We don't specify what port to use on entry-1 so it will fallback to default: 1234
 # It is not necessary to set a custom port, it is just more visual when it comes to seeing the circuit
  entry-1:
    build:
      context: .
      dockerfile: entry/entry.Dockerfile
    depends_on:
      directory:
        condition: service_healthy

  entry-2: 
    build:
      context: .
      dockerfile: entry/entry.Dockerfile
    environment:
      - PORT=9997
    depends_on:
      directory:
        condition: service_healthy

# ==================

# ==== RELAY NODES ====

  relay-0:
    build:
      context: .
      dockerfile: relay/relay.Dockerfile
    environment:
      - PORT=9989
    depends_on:
      directory:
        condition: service_healthy

  relay-1:
    build:
      context: .
      dockerfile: relay/relay.Dockerfile
    depends_on:
      directory:
        condition: service_healthy

  relay-2:
    build:
      context: .
      dockerfile: relay/relay.Dockerfile
    environment:
      - PORT=9987
    depends_on:
      directory:
        condition: service_healthy

# ==================

# ==== EXIT NODES ====

  exit-0:
    build:
      context: .
      dockerfile: exit/exit.Dockerfile
    environment:
      - PORT=3454
    depends_on:
      directory:
        condition: service_healthy

  exit-1:
    build:
      context: .
      dockerfile: exit/exit.Dockerfile
    depends_on:
      directory:
        condition: service_healthy

  exit-2:
    build:
      context: .
      dockerfile: exit/exit.Dockerfile
    environment:
      - PORT=259
    depends_on:
      directory:
        condition: service_healthy
        
# ==================